--TAO CSDL
CREATE DATABASE QLQUANCAFE
ON PRIMARY
(
	NAME=QLQUANCAFE_DATA,
	FILENAME='D:\study\windows\QLCAFE\QLQUANCAFE_SQL\QLQUANCAFE_DATA.MDF',
	SIZE=8 MB,
	MAXSIZE =10MB,
	FILEGROWTH=1MB
)
LOG ON
(
	NAME=QLQUANCAFE_LOG,
	FILENAME='D:\study\windows\QLCAFE\QLQUANCAFE_SQL\QLQUANCAFE_LOG.LDF',
	SIZE=6MB,
	MAXSIZE =8MB,
	FILEGROWTH=1MB
)

--MO  QLQUANCAFE
USE QLQUANCAFE
GO

--ten thuc uong,ban,danh muc  ,tai khoan,hoa don,chi tiet hoa don
CREATE TABLE BAN
(
	MABAN INT IDENTITY NOT NULL PRIMARY KEY,
	TENBAN NVARCHAR(100) NOT NULL DEFAULT N'CHUA DAT TEN',
	TRANGTHAI NVARCHAR(100) NOT NULL --TRONG || CO NGUOI
)
GO

CREATE TABLE TAIKHOAN
(
	MATAIKHOAN INT IDENTITY NOT NULL PRIMARY KEY,
	TENDANGNHAP NVARCHAR(100) NOT NULL,
	MATKHAU NVARCHAR(1000) NOT NULL,
	TENHIENTHI NVARCHAR(100) NOT NULL,
	LOAITAIKHOAN INT NOT NULL
)
GO

CREATE TABLE DANHSACHMON
(
	MAMON INT IDENTITY NOT NULL PRIMARY KEY,
	TEN NVARCHAR(100) DEFAULT N'CHUA DAT TEN'
)
GO

CREATE TABLE THUCUONG
(
	MAMON INT IDENTITY NOT NULL PRIMARY KEY,
	TEN NVARCHAR(100) DEFAULT N'CHUA DAT TEN',
	MADSMON INT NOT NULL,
	GIA FLOAT NOT NULL DEFAULT 0,

	FOREIGN KEY(MADSMON) REFERENCES DANHSACHMON(MAMON)
)
GO

CREATE TABLE HOADON
(
	MAHD INT IDENTITY NOT NULL PRIMARY KEY,
	THOIGIANVAO DATE NOT NULL,
	THOIGIANRA DATE,
	MABAN INT NOT NULL,
	TRANGTHAI INT NOT NULL DEFAULT 0 ,--1:DA THANH TOAN ||0:CHUA THANH TOAN

	FOREIGN KEY(MABAN) REFERENCES BAN(MABAN)
)
GO

CREATE TABLE CHITIETHOADON
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	MAHD INT NOT NULL,
	MAMON INT NOT NULL,
	DEM INT NOT NULL DEFAULT 0,

	FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	FOREIGN KEY(MAMON) REFERENCES THUCUONG(MAMON)
)
GO


CREATE TABLE THONGTINKHACHHANG 
(
	MAKHACHHANG NVARCHAR(30) PRIMARY KEY,
	TENKHACHHANG NVARCHAR(50)

)
INSERT INTO TAIKHOAN VALUES( N'TK2',N'2',N'KHACH HANG 2',1)

SELECT *FROM TAIKHOAN

SELECT *FROM TAIKHOAN WHERE (TENDANGNHAP=N'TK2' AND MATKHAU=N'2')

--CREATE PROC USP_GETTAIKHOANBYTENDANGNHAP
--@TENDANGNHAP NVARCHAR(100)
--AS
--BEGIN
-- SELECT *FROM TAIKHOAN WHERE TENDANGNHAP=@TENDANGNHAP
--END
--GO

--EXECUTE USP_GETTAIKHOANBYTENDANGNHAP @TENDANGNHAP=N'TK2'


